name: create_plan
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.2.0
  firebase_core: ^2.4.0
  bloc: ^8.1.0
  meta: ^1.8.0
  flutter_driver:
    sdk: flutter
  go_router: ^5.2.4
  firebase_auth: ^4.2.0
  hive: ^2.2.3
  shared_preferences: ^2.0.15
  flutter_bloc: ^8.1.1
  flex_color_scheme: ^6.1.1
  google_fonts: ^3.0.1
  path: ^1.8.2
  get_it: ^7.2.0
  dartz: ^0.10.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

