// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6BFFAicKqP7YPKvCAvCiCsp5K57QB2EY',
    appId: '1:556383153172:web:f5aaae18ca61f296200b01',
    messagingSenderId: '556383153172',
    projectId: 'createplan-6006c',
    authDomain: 'createplan-6006c.firebaseapp.com',
    storageBucket: 'createplan-6006c.appspot.com',
    measurementId: 'G-3PPLPZTSNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzbPpJz5oQ_9Rt5pNVtOFcDKUUZ9ElEtw',
    appId: '1:556383153172:android:60546e4e4eb23adb200b01',
    messagingSenderId: '556383153172',
    projectId: 'createplan-6006c',
    storageBucket: 'createplan-6006c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtD-Un63gebJsnOl6MgpnYCk5ll5nRX5Q',
    appId: '1:556383153172:ios:39506e47548375f6200b01',
    messagingSenderId: '556383153172',
    projectId: 'createplan-6006c',
    storageBucket: 'createplan-6006c.appspot.com',
    iosClientId: '556383153172-ajrft8fh9t7r0jq7isa6glr1saa2d89j.apps.googleusercontent.com',
    iosBundleId: 'com.example.createPlan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtD-Un63gebJsnOl6MgpnYCk5ll5nRX5Q',
    appId: '1:556383153172:ios:39506e47548375f6200b01',
    messagingSenderId: '556383153172',
    projectId: 'createplan-6006c',
    storageBucket: 'createplan-6006c.appspot.com',
    iosClientId: '556383153172-ajrft8fh9t7r0jq7isa6glr1saa2d89j.apps.googleusercontent.com',
    iosBundleId: 'com.example.createPlan',
  );
}
