name: Build IOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_ios:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.9"
          channel: "stable"
          architecture: x64
      - run: flutter doctor
      - run: flutter pub get

      - run: flutter build ios --release --no-codesign
