name: CI Android

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  integration_test_android:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.9"
          channel: stable
      - uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: gradle
      - run: flutter doctor -v
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          script: flutter drive --target=test_driver/app.dart
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: my-artifact
          path: ./screenshots/*
